# Generated by Django 4.2.20 on 2025-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointmentid', models.AutoField(db_column='AppointmentID', primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField(blank=True, db_column='AppointmentDate', null=True)),
                ('appointmenttime', models.TimeField(blank=True, db_column='AppointmentTime', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=9, null=True)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctorid', models.AutoField(db_column='DoctorID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, db_column='Specialization', max_length=50, null=True)),
                ('contactinfo', models.CharField(blank=True, db_column='ContactInfo', max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, db_column='Experience', null=True)),
            ],
            options={
                'db_table': 'Doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowAppointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'MediFlow_appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowBilling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'MediFlow_billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'MediFlow_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowDoctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('availability', models.IntegerField()),
            ],
            options={
                'db_table': 'MediFlow_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowMedicalrecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'MediFlow_medicalrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediflowPatient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'MediFlow_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientid', models.AutoField(db_column='PatientID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=6, null=True)),
                ('contactinfo', models.CharField(blank=True, db_column='ContactInfo', max_length=50, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('medicalhistory', models.TextField(blank=True, db_column='MedicalHistory', null=True)),
            ],
            options={
                'db_table': 'Patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(db_column='StaffID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('role', models.CharField(db_column='Role', max_length=13)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('contactinfo', models.CharField(blank=True, db_column='ContactInfo', max_length=50, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=2, max_digits=10, null=True)),
                ('workschedule', models.TextField(blank=True, db_column='WorkSchedule', null=True)),
                ('joiningdate', models.DateField(blank=True, db_column='JoiningDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=8, null=True)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
    ]
